server:
  port: 9001

spring:
  datasource:
    username: root
#    password: HAKJ123!@#hihi!!
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3307/wms_hongan_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    url: jdbc:mysql://111.229.119.100:3307/wms_hongan_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: select 1
      pool-name: QHDBPOOL
      maximum-pool-size: 16
      minimum-idle: 4

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
#    host: 127.0.0.1
#    host: redis
    host: 111.229.119.100
    # Redis服务器连接端口
    port: 6888
#    port: 6379
    # Redis 密码
    password:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  level:
    root: INFO
    com.hongan.*: INFO
  file:
    path: ./logs
